//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clasharp {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Clasharp.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string titleDashboard {
            get {
                return ResourceManager.GetString("titleDashboard", resourceCulture);
            }
        }
        
        public static string titleConnections {
            get {
                return ResourceManager.GetString("titleConnections", resourceCulture);
            }
        }
        
        public static string titleProxies {
            get {
                return ResourceManager.GetString("titleProxies", resourceCulture);
            }
        }
        
        public static string titleLogs {
            get {
                return ResourceManager.GetString("titleLogs", resourceCulture);
            }
        }
        
        public static string titleProfiles {
            get {
                return ResourceManager.GetString("titleProfiles", resourceCulture);
            }
        }
        
        public static string titleSettings {
            get {
                return ResourceManager.GetString("titleSettings", resourceCulture);
            }
        }
        
        public static string titleRules {
            get {
                return ResourceManager.GetString("titleRules", resourceCulture);
            }
        }
        
        public static string switchStopped {
            get {
                return ResourceManager.GetString("switchStopped", resourceCulture);
            }
        }
        
        public static string switchStarted {
            get {
                return ResourceManager.GetString("switchStarted", resourceCulture);
            }
        }
        
        public static string dashUpload {
            get {
                return ResourceManager.GetString("dashUpload", resourceCulture);
            }
        }
        
        public static string dashDownload {
            get {
                return ResourceManager.GetString("dashDownload", resourceCulture);
            }
        }
        
        public static string dashUploadTotal {
            get {
                return ResourceManager.GetString("dashUploadTotal", resourceCulture);
            }
        }
        
        public static string dashDownloadTotal {
            get {
                return ResourceManager.GetString("dashDownloadTotal", resourceCulture);
            }
        }
        
        public static string dashActiveConnections {
            get {
                return ResourceManager.GetString("dashActiveConnections", resourceCulture);
            }
        }
        
        public static string titlePolicyGroups {
            get {
                return ResourceManager.GetString("titlePolicyGroups", resourceCulture);
            }
        }
        
        public static string titleProviders {
            get {
                return ResourceManager.GetString("titleProviders", resourceCulture);
            }
        }
        
        public static string settingSystemProxy {
            get {
                return ResourceManager.GetString("settingSystemProxy", resourceCulture);
            }
        }
        
        public static string settingStartWithSystem {
            get {
                return ResourceManager.GetString("settingStartWithSystem", resourceCulture);
            }
        }
        
        public static string settingTheme {
            get {
                return ResourceManager.GetString("settingTheme", resourceCulture);
            }
        }
        
        public static string settingManageCoreLibrary {
            get {
                return ResourceManager.GetString("settingManageCoreLibrary", resourceCulture);
            }
        }
        
        public static string settingCoreServiceStatus {
            get {
                return ResourceManager.GetString("settingCoreServiceStatus", resourceCulture);
            }
        }
        
        public static string settingUseCoreService {
            get {
                return ResourceManager.GetString("settingUseCoreService", resourceCulture);
            }
        }
        
        public static string settingExternalController {
            get {
                return ResourceManager.GetString("settingExternalController", resourceCulture);
            }
        }
        
        public static string settingTun {
            get {
                return ResourceManager.GetString("settingTun", resourceCulture);
            }
        }
        
        public static string settingAllowLan {
            get {
                return ResourceManager.GetString("settingAllowLan", resourceCulture);
            }
        }
        
        public static string settingIpv6 {
            get {
                return ResourceManager.GetString("settingIpv6", resourceCulture);
            }
        }
        
        public static string settingMixedPort {
            get {
                return ResourceManager.GetString("settingMixedPort", resourceCulture);
            }
        }
        
        public static string settingReloadConfig {
            get {
                return ResourceManager.GetString("settingReloadConfig", resourceCulture);
            }
        }
        
        public static string settingUseSystemCore {
            get {
                return ResourceManager.GetString("settingUseSystemCore", resourceCulture);
            }
        }
        
        public static string txtFilterProxies {
            get {
                return ResourceManager.GetString("txtFilterProxies", resourceCulture);
            }
        }
        
        public static string txtHealthCheck {
            get {
                return ResourceManager.GetString("txtHealthCheck", resourceCulture);
            }
        }
        
        public static string txtCheckUpdate {
            get {
                return ResourceManager.GetString("txtCheckUpdate", resourceCulture);
            }
        }
        
        public static string txtCloseAllConnection {
            get {
                return ResourceManager.GetString("txtCloseAllConnection", resourceCulture);
            }
        }
        
        public static string txtTotalTraffic {
            get {
                return ResourceManager.GetString("txtTotalTraffic", resourceCulture);
            }
        }
        
        public static string txtNewProfile {
            get {
                return ResourceManager.GetString("txtNewProfile", resourceCulture);
            }
        }
        
        public static string txtType {
            get {
                return ResourceManager.GetString("txtType", resourceCulture);
            }
        }
        
        public static string txtName {
            get {
                return ResourceManager.GetString("txtName", resourceCulture);
            }
        }
        
        public static string txtDescription {
            get {
                return ResourceManager.GetString("txtDescription", resourceCulture);
            }
        }
        
        public static string txtImportFrom {
            get {
                return ResourceManager.GetString("txtImportFrom", resourceCulture);
            }
        }
        
        public static string txtSelectFile {
            get {
                return ResourceManager.GetString("txtSelectFile", resourceCulture);
            }
        }
        
        public static string txtSave {
            get {
                return ResourceManager.GetString("txtSave", resourceCulture);
            }
        }
        
        public static string txtUrl {
            get {
                return ResourceManager.GetString("txtUrl", resourceCulture);
            }
        }
        
        public static string txtAutoUpdateMinutes {
            get {
                return ResourceManager.GetString("txtAutoUpdateMinutes", resourceCulture);
            }
        }
        
        public static string txtEditProfile {
            get {
                return ResourceManager.GetString("txtEditProfile", resourceCulture);
            }
        }
        
        public static string txtManage {
            get {
                return ResourceManager.GetString("txtManage", resourceCulture);
            }
        }
        
        public static string txtInstall {
            get {
                return ResourceManager.GetString("txtInstall", resourceCulture);
            }
        }
        
        public static string txtUninstall {
            get {
                return ResourceManager.GetString("txtUninstall", resourceCulture);
            }
        }
        
        public static string txtStart {
            get {
                return ResourceManager.GetString("txtStart", resourceCulture);
            }
        }
        
        public static string txtStop {
            get {
                return ResourceManager.GetString("txtStop", resourceCulture);
            }
        }
        
        public static string txtSetAutoStart {
            get {
                return ResourceManager.GetString("txtSetAutoStart", resourceCulture);
            }
        }
    }
}
