//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clasharp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Clasharp.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Connections.
        /// </summary>
        public static string dashActiveConnections {
            get {
                return ResourceManager.GetString("dashActiveConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string dashDownload {
            get {
                return ResourceManager.GetString("dashDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Total.
        /// </summary>
        public static string dashDownloadTotal {
            get {
                return ResourceManager.GetString("dashDownloadTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string dashUpload {
            get {
                return ResourceManager.GetString("dashUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Total.
        /// </summary>
        public static string dashUploadTotal {
            get {
                return ResourceManager.GetString("dashUploadTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Lan.
        /// </summary>
        public static string settingAllowLan {
            get {
                return ResourceManager.GetString("settingAllowLan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core Service Status.
        /// </summary>
        public static string settingCoreServiceStatus {
            get {
                return ResourceManager.GetString("settingCoreServiceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Controller.
        /// </summary>
        public static string settingExternalController {
            get {
                return ResourceManager.GetString("settingExternalController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ipv6.
        /// </summary>
        public static string settingIpv6 {
            get {
                return ResourceManager.GetString("settingIpv6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Core Library.
        /// </summary>
        public static string settingManageCoreLibrary {
            get {
                return ResourceManager.GetString("settingManageCoreLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixed Port.
        /// </summary>
        public static string settingMixedPort {
            get {
                return ResourceManager.GetString("settingMixedPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload Config.
        /// </summary>
        public static string settingReloadConfig {
            get {
                return ResourceManager.GetString("settingReloadConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start With System.
        /// </summary>
        public static string settingStartWithSystem {
            get {
                return ResourceManager.GetString("settingStartWithSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Proxy.
        /// </summary>
        public static string settingSystemProxy {
            get {
                return ResourceManager.GetString("settingSystemProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string settingTheme {
            get {
                return ResourceManager.GetString("settingTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tun.
        /// </summary>
        public static string settingTun {
            get {
                return ResourceManager.GetString("settingTun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Core Service.
        /// </summary>
        public static string settingUseCoreService {
            get {
                return ResourceManager.GetString("settingUseCoreService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started.
        /// </summary>
        public static string switchStarted {
            get {
                return ResourceManager.GetString("switchStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped.
        /// </summary>
        public static string switchStopped {
            get {
                return ResourceManager.GetString("switchStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connections.
        /// </summary>
        public static string titleConnections {
            get {
                return ResourceManager.GetString("titleConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string titleDashboard {
            get {
                return ResourceManager.GetString("titleDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        public static string titleLogs {
            get {
                return ResourceManager.GetString("titleLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Groups.
        /// </summary>
        public static string titlePolicyGroups {
            get {
                return ResourceManager.GetString("titlePolicyGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles.
        /// </summary>
        public static string titleProfiles {
            get {
                return ResourceManager.GetString("titleProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Providers.
        /// </summary>
        public static string titleProviders {
            get {
                return ResourceManager.GetString("titleProviders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxies.
        /// </summary>
        public static string titleProxies {
            get {
                return ResourceManager.GetString("titleProxies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules.
        /// </summary>
        public static string titleRules {
            get {
                return ResourceManager.GetString("titleRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string titleSettings {
            get {
                return ResourceManager.GetString("titleSettings", resourceCulture);
            }
        }
    }
}
